name: npm-build工作并推送DockeHub
on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: npm-build

    steps:
    - name: Checkout
      uses: actions/checkout@v4

#    - name: 安装依赖
#      run: npm install
#
#    - name: 项目打包
#      run: npm run build
#
#    - name: 部署
#      uses: JamesIves/github-pages-deploy-action@v4
#      with:
#        branch: gh-pages
#        folder: build

    - name: Login in Dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Push to Dockerhub
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/action:latest