name: Make package
on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: npm-build

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: npm-build
      run: npm install && npm run build

    - name: Apply
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: build